name: SLSA builder Go
on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - "*"

permissions: read-all

jobs:
  # Trusted builder.
  build:
    permissions:
      id-token: write
      contents: write
      actions: read
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml
    with:
      go-version: 1.20
