name: SLSA provenance
on: workflow_dispatch


jobs:

  # Trusted builder.
  build:
    permissions:
      id-token: write
      contents: read
    
    uses: slsa-framework/slsa-github-generator/blob/main/.github/workflows/builder_go_slsa3.yml@main
    with:
      go-version: 1.17
