name: SLSA provenance
on: workflow_dispatch


 jobs:

  # Trusted builder.
  build:
    permissions:
      id-token: write
      contents: read
    needs: checkout
    uses: slsa-framework/slsa-github-generator-go/.github/workflows/builder.yml@main
    with:
      go-version: 1.17
